name: Continuous Deployment for Flutter applications

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    uses: fermi-ad/.github/.github/workflows/flutter-deploy.yaml@3c482bac81ef727d058e0aecd8b93d515da6767e
    secrets: inherit
