name: Continuous Deployment for Flutter applications

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    uses: fermi-ad/.github/.github/workflows/flutter-deploy.yaml@9a59891c27133b3b50a9b0d3b8a355611f45126b
    secrets: inherit
